### ISSUE TITLE
Getting error while installing No podspec found for `DudodCapacitorPluginInstallReferrer`

### ISSUE THREAD

**Issue by yugandhargangu** [dmitry-udod/capacitor-plugin-install-referrer#1]
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] No podspec found for `DudodCapacitorPluginInstallReferrer` in
        `../../node_modules/@dudod/capacitor-plugin-install-referrer`

**Comment by dmitry-udod** [comment]
@yugandhargangu Hi!  Could you try the updated version 1.0.13

**Comment by yugandhargangu** [comment]
Still getiing same error. Actually **DudodCapacitorPluginInstallReferrer.podspec** file is not being present in **node_modules/@dudod/capacitor-plugin-install-referrer** location. Mostly npm ignoring the required file.

This is because your **package.json** file contains **TogetherpriceCapacitorPluginInstallReferrer.podspec** file name in row 10 not the **DudodCapacitorPluginInstallReferrer.podspec** file name. Please update package.json file.

**Comment by dmitry-udod** [comment]
Ohh I see. Done. Published new version (1.0.14)
